const timelineContents = [
    {
        id: 1,
        title: "It Intern | PSEG",
        location: "Newark, New Jersey",
        description: "Gained hands-on experience with the Software Development Life Cycle (SDLC).",
        buttonText: "Details",
        date: "June, 2024 - August, 2024",
        icon: "work",
        color: "green",
        tech: ["MuleSoft", "GitHub", "Postman", "ServiceNow", "SharePoint"],
    },
    {
        id: 2,
        title: "Technical Analyst/Prograamer | NJ Transit",
        location: "Newark, New Jersey",
        description: "Developed and tested responsive websites ensuring user-centric design and functionality.",
        buttonText: "Details",
        date: "January, 2024 - May, 2024",
        icon: "work",
        color: "teal",
        tech: ["React", "TypeScript", "Figma", "Jira", "Confluence"],
    },
    {
        id: 3,
        title: "It Intern | PSEG",
        location: "Newark, New Jersey",
        description: "Gained hands-on experience with the Software Development Life Cycle (SDLC).",
        buttonText: "Details",
        date: "June, 2024 - August, 2024",
        icon: "work",
        color: "emerald",
        tech: ["MuleSoft", "GitHub", "Postman", "ServiceNow", "SharePoint"],
    },
    {
        id: 4,
        title: "It Intern | PSEG",
        location: "Newark, New Jersey",
        description: "Gained hands-on experience with the Software Development Life Cycle (SDLC).",
        buttonText: "Details",
        date: "June, 2024 - August, 2024",
        icon: "work",
        color: "green",
        tech: ["MuleSoft", "GitHub", "Postman", "ServiceNow", "SharePoint"],
    },
    {
        id: 5,
        title: "It Intern | PSEG",
        location: "Newark, New Jersey",
        description: "Gained hands-on experience with the Software Development Life Cycle (SDLC).",
        buttonText: "Details",
        date: "June, 2024 - August, 2024",
        icon: "work",
        color: "teal",
        tech: ["MuleSoft", "GitHub", "Postman", "ServiceNow", "SharePoint"],
    },

];

export default timelineContents;